// lib/data/asmaul_husna.dart
// Full 99 Names of Allah: Arabic + Transliteration

class DivineName {
  final int id;
  final String arabic;
  final String transliteration;

  const DivineName({
    required this.id,
    required this.arabic,
    required this.transliteration,
  });
}

const List<DivineName> asmaulHusna = [
  DivineName(id: 1, arabic: 'اللَّهُ', transliteration: 'Allah'),
  DivineName(id: 2, arabic: 'الرَّحْمَنُ', transliteration: 'Ar-Rahman'),
  DivineName(id: 3, arabic: 'الرَّحِيمُ', transliteration: 'Ar-Rahim'),
  DivineName(id: 4, arabic: 'المَلِكُ', transliteration: 'Al-Malik'),
  DivineName(id: 5, arabic: 'القُدُّوسُ', transliteration: 'Al-Quddus'),
  DivineName(id: 6, arabic: 'السَّلَامُ', transliteration: 'As-Salam'),
  DivineName(id: 7, arabic: 'المُؤْمِنُ', transliteration: 'Al-Mu’min'),
  DivineName(id: 8, arabic: 'المُهَيْمِنُ', transliteration: 'Al-Muhaymin'),
  DivineName(id: 9, arabic: 'العَزِيزُ', transliteration: 'Al-Aziz'),
  DivineName(id: 10, arabic: 'الجَبَّارُ', transliteration: 'Al-Jabbar'),
  DivineName(id: 11, arabic: 'المُتَكَبِّرُ', transliteration: 'Al-Mutakabbir'),
  DivineName(id: 12, arabic: 'الخَالِقُ', transliteration: 'Al-Khaliq'),
  DivineName(id: 13, arabic: 'البَارِىءُ', transliteration: 'Al-Bari'),
  DivineName(id: 14, arabic: 'المُصَوِّرُ', transliteration: 'Al-Musawwir'),
  DivineName(id: 15, arabic: 'الغَفَّارُ', transliteration: 'Al-Ghaffar'),
  DivineName(id: 16, arabic: 'القَهَّارُ', transliteration: 'Al-Qahhar'),
  DivineName(id: 17, arabic: 'الوَهَّابُ', transliteration: 'Al-Wahhab'),
  DivineName(id: 18, arabic: 'الرَّزَّاقُ', transliteration: 'Ar-Razzaq'),
  DivineName(id: 19, arabic: 'الفَتَّاحُ', transliteration: 'Al-Fattah'),
  DivineName(id: 20, arabic: 'العَلِيمُ', transliteration: 'Al-Alim'),
  DivineName(id: 21, arabic: 'القَابِضُ', transliteration: 'Al-Qabid'),
  DivineName(id: 22, arabic: 'البَاسِطُ', transliteration: 'Al-Basit'),
  DivineName(id: 23, arabic: 'الخَافِضُ', transliteration: 'Al-Khafid'),
  DivineName(id: 24, arabic: 'الرَّافِعُ', transliteration: 'Ar-Rafi‘'),
  DivineName(id: 25, arabic: 'المُعِزُّ', transliteration: 'Al-Mu‘izz'),
  DivineName(id: 26, arabic: 'المُذِلُّ', transliteration: 'Al-Mudhill'),
  DivineName(id: 27, arabic: 'السَّمِيعُ', transliteration: 'As-Sami‘'),
  DivineName(id: 28, arabic: 'البَصِيرُ', transliteration: 'Al-Basir'),
  DivineName(id: 29, arabic: 'الحَكَمُ', transliteration: 'Al-Hakam'),
  DivineName(id: 30, arabic: 'العَدْلُ', transliteration: 'Al-‘Adl'),
  DivineName(id: 31, arabic: 'اللَّطِيفُ', transliteration: 'Al-Latif'),
  DivineName(id: 32, arabic: 'الخَبِيرُ', transliteration: 'Al-Khabir'),
  DivineName(id: 33, arabic: 'الحَلِيمُ', transliteration: 'Al-Halim'),
  DivineName(id: 34, arabic: 'العَظِيمُ', transliteration: 'Al-Azim'),
  DivineName(id: 35, arabic: 'الغَفُورُ', transliteration: 'Al-Ghafur'),
  DivineName(id: 36, arabic: 'الشَّكُورُ', transliteration: 'Ash-Shakur'),
  DivineName(id: 37, arabic: 'العَلِيُّ', transliteration: 'Al-Aliyy'),
  DivineName(id: 38, arabic: 'الكَبِيرُ', transliteration: 'Al-Kabir'),
  DivineName(id: 39, arabic: 'الحَفِيظُ', transliteration: 'Al-Hafiz'),
  DivineName(id: 40, arabic: 'المُقِيتُ', transliteration: 'Al-Muqit'),
  DivineName(id: 41, arabic: 'الحَسِيبُ', transliteration: 'Al-Hasib'),
  DivineName(id: 42, arabic: 'الجَلِيلُ', transliteration: 'Al-Jalil'),
  DivineName(id: 43, arabic: 'الكَرِيمُ', transliteration: 'Al-Karim'),
  DivineName(id: 44, arabic: 'الرَّقِيبُ', transliteration: 'Ar-Raqib'),
  DivineName(id: 45, arabic: 'المُجِيبُ', transliteration: 'Al-Mujib'),
  DivineName(id: 46, arabic: 'الوَاسِعُ', transliteration: 'Al-Wasi‘'),
  DivineName(id: 47, arabic: 'الحَكِيمُ', transliteration: 'Al-Hakim'),
  DivineName(id: 48, arabic: 'الوَدُودُ', transliteration: 'Al-Wadud'),
  DivineName(id: 49, arabic: 'المَجِيدُ', transliteration: 'Al-Majid'),
  DivineName(id: 50, arabic: 'البَاعِثُ', transliteration: 'Al-Ba‘ith'),
  DivineName(id: 51, arabic: 'الشَّهِيدُ', transliteration: 'Ash-Shahid'),
  DivineName(id: 52, arabic: 'الحَقُّ', transliteration: 'Al-Haqq'),
  DivineName(id: 53, arabic: 'الوَكِيلُ', transliteration: 'Al-Wakil'),
  DivineName(id: 54, arabic: 'القَوِيُّ', transliteration: 'Al-Qawiyy'),
  DivineName(id: 55, arabic: 'المَتِينُ', transliteration: 'Al-Matin'),
  DivineName(id: 56, arabic: 'الوَلِيُّ', transliteration: 'Al-Waliyy'),
  DivineName(id: 57, arabic: 'الحَمِيدُ', transliteration: 'Al-Hamid'),
  DivineName(id: 58, arabic: 'المُحْصِي', transliteration: 'Al-Muhsi'),
  DivineName(id: 59, arabic: 'المُبْدِىءُ', transliteration: 'Al-Mubdi‘'),
  DivineName(id: 60, arabic: 'المُعِيدُ', transliteration: 'Al-Mu‘id'),
  DivineName(id: 61, arabic: 'المُحْيِي', transliteration: 'Al-Muhyi'),
  DivineName(id: 62, arabic: 'المُمِيتُ', transliteration: 'Al-Mumit'),
  DivineName(id: 63, arabic: 'الحَيُّ', transliteration: 'Al-Hayy'),
  DivineName(id: 64, arabic: 'القَيُّومُ', transliteration: 'Al-Qayyum'),
  DivineName(id: 65, arabic: 'الوَاجِدُ', transliteration: 'Al-Wajid'),
  DivineName(id: 66, arabic: 'المَاجِدُ', transliteration: 'Al-Majid'),
  DivineName(id: 67, arabic: 'الوَاحِدُ', transliteration: 'Al-Wahid'),
  DivineName(id: 68, arabic: 'الصَّمَدُ', transliteration: 'As-Samad'),
  DivineName(id: 69, arabic: 'القَادِرُ', transliteration: 'Al-Qadir'),
  DivineName(id: 70, arabic: 'المُقْتَدِرُ', transliteration: 'Al-Muqtadir'),
  DivineName(id: 71, arabic: 'المُقَدِّمُ', transliteration: 'Al-Muqaddim'),
  DivineName(id: 72, arabic: 'المُؤَخِّرُ', transliteration: 'Al-Mu’akhkhir'),
  DivineName(id: 73, arabic: 'الأَوَّلُ', transliteration: 'Al-Awwal'),
  DivineName(id: 74, arabic: 'الآخِرُ', transliteration: 'Al-Akhir'),
  DivineName(id: 75, arabic: 'الظَّاهِرُ', transliteration: 'Az-Zahir'),
  DivineName(id: 76, arabic: 'البَاطِنُ', transliteration: 'Al-Batin'),
  DivineName(id: 77, arabic: 'الوَالِي', transliteration: 'Al-Wali'),
  DivineName(id: 78, arabic: 'المُتَعَالِ', transliteration: 'Al-Muta‘ali'),
  DivineName(id: 79, arabic: 'البَرُّ', transliteration: 'Al-Barr'),
  DivineName(id: 80, arabic: 'التَّوَّابُ', transliteration: 'At-Tawwab'),
  DivineName(id: 81, arabic: 'المُنْتَقِمُ', transliteration: 'Al-Muntaqim'),
  DivineName(id: 82, arabic: 'العَفُوُّ', transliteration: 'Al-‘Afuww'),
  DivineName(id: 83, arabic: 'الرَّءُوفُ', transliteration: 'Ar-Ra’uf'),
  DivineName(
    id: 84,
    arabic: 'مَالِكُ المُلْكِ',
    transliteration: 'Malik-ul-Mulk',
  ),
  DivineName(
    id: 85,
    arabic: 'ذُوالجَلَالِ وَالإِكْرَامِ',
    transliteration: 'Dhul-Jalali wal-Ikram',
  ),
  DivineName(id: 86, arabic: 'المُقْسِطُ', transliteration: 'Al-Muqsit'),
  DivineName(id: 87, arabic: 'الجَامِعُ', transliteration: 'Al-Jami‘'),
  DivineName(id: 88, arabic: 'الغَنِيُّ', transliteration: 'Al-Ghani'),
  DivineName(id: 89, arabic: 'المُغْنِيُّ', transliteration: 'Al-Mughni'),
  DivineName(id: 90, arabic: 'المَانِعُ', transliteration: 'Al-Mani‘'),
  DivineName(id: 91, arabic: 'الضَّارُ', transliteration: 'Ad-Darr'),
  DivineName(id: 92, arabic: 'النَّافِعُ', transliteration: 'An-Nafi‘'),
  DivineName(id: 93, arabic: 'النُّورُ', transliteration: 'An-Nur'),
  DivineName(id: 94, arabic: 'الهَادِي', transliteration: 'Al-Hadi'),
  DivineName(id: 95, arabic: 'البَدِيعُ', transliteration: 'Al-Badi‘'),
  DivineName(id: 96, arabic: 'البَاقِي', transliteration: 'Al-Baqi'),
  DivineName(id: 97, arabic: 'الوَارِثُ', transliteration: 'Al-Warith'),
  DivineName(id: 98, arabic: 'الرَّشِيدُ', transliteration: 'Ar-Rashid'),
  DivineName(id: 99, arabic: 'الصَّبُورُ', transliteration: 'As-Sabur'),
];

// Convenience: Arabic-only list
final List<String> asmaulHusnaArabic = asmaulHusna
    .map((n) => n.arabic)
    .toList();
